version: '2'
services:

  ## Config Servers
  config01:
    image: mongo
    command: mongod --port 27017 --configsvr --replSet configserver --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts

  ## Shards
  shard01a:
    image: mongo
    command: mongod --port 27018 --shardsvr --replSet shard01 --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts

  ## Router
  router:
    image: mongo
    command: mongos --port 27017 --configdb configserver/config01:27017
    ports:
      - "27017:27017"
    volumes:
      - ./scripts:/scripts
    depends_on:
      - config01
      - shard01a
